code-volume2:
  image: debian
  volumes:
    - .:/var/www/html
  ports:
    - "8090:80"
  command: bash


web:
  image: webdevops/php-apache-dev
  command: php -S 0.0.0.0:8000 -t /var/www/html

  ports:
    - "8000:8000"
  volumes_from:
    - code-volume2
