code-volume2:
  image: debian
  volumes:
    - .:/var/www/html

web:
  image: pinuaga/debian_9_apache
  command: php -S 0.0.0.0:8000 -t /var/www/html
  ports:
    - "8000:80"
  volumes_from:
    - code-volume2
